apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "bash"
spec:
  uprobes:
  - path: "/procRoot/<PID>/root/bin/bash"
    symbols:
    - "readline"
    args:
    - index: 0
      type: "string"
